### PR TITLE
Refactor receiver_kernel

### PR DESCRIPTION
**Pull request by noc0lour**
receiver_kernel now links against non-GNURadio libraries and follows modulator concept. Same concept is implemented in pygfdm.gfdm_receiver. A test proves both implementation match. A visual test also proves the receiver is now compatible with simple_modulator. QA for the whole chain and SIC implementation are still missing.
@jdemel: You think the receiver_kernel_cc works for you?

### CODE REVIEW

**Comment by jdemel** [comment]
This looks all fine. I'd recommend to update the examples, demo + demo_sync though!
It compiles and all tests pass on my machine, but the examples seem to be broken.

**Comment by jdemel** [comment]
@noc0lour I assume my sync work should be made ready to merge after this merge. Thus, I'll prepare everything and will update my refs as soon as this work is merged.

**Comment by noc0lour** [comment]
> This looks all fine. I'd recommend to update the examples, demo +
> demo_sync though!
> @jdemel I'm working on updating/refactoring examples and adding a
> transceiver-example.
> I'll add them and then merge this branch into master.

**Comment by jdemel** [comment]
_thumbsup_

**Pull request merged**
